services:
  api:
    container_name: mahjong_tile_dealing
    volumes:
      - ./app:/app
      - ./img:/app/img
      - ./.env:/app/.env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
