name: Run pytest
on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout
        uses: actions/checkout@v2

      # Pythonの環境をセットアップ
      - name: Set up Python 3.13
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      # pytestをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install --no-cache-dir --upgrade -r ./app/requirements.txt

      # pytest -> JUnit xml形式で結果を出力
      - name: PyTest
        run: |
          python -m pytest app/main_test.py --junit-xml results/pytest.xml
        continue-on-error: true
